# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-notify-my-android"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ken Pepple"]
  s.date = "2013-02-17"
  s.description = "Send notifications to Android devices via the Notify My Android API. Details about the API are available at https://nma.usk.bz/api.php ."
  s.email = "ken.pepple@rabbityard.com"
  s.executables = ["notify-my-android"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/notify-my-android",
    "lib/ruby-notify-my-android.rb",
    "lib/ruby-notify-my-android/notification.rb",
    "lib/ruby-notify-my-android/request.rb",
    "lib/ruby-notify-my-android/response.rb",
    "ruby-notify-my-android.gemspec",
    "test/helper.rb",
    "test/test_ruby-notify-my-android.rb"
  ]
  s.homepage = "http://github.com/slashk/ruby-notify-my-android"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Send notifications to Android devices via the Notify My Android API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 1.0.15"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, ["= 0.9.11"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 1.0.15"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, ["= 0.9.11"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 1.0.15"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, ["= 0.9.11"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

